baseURL: "http://www.virtumaster.com"
title: "Virtualization Masters"
defaultContentLanguage: en
languages:
  en:
    lang: en
    languageName: English
    weight: 1
MetaDataFormat: "yaml"
theme: "claritylight"

permalinks:
  posts: /:year/:month/:title/

sectionPagesMenu: "main"
