name = "Claritylight"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "VMware Clarity UI Light Theme for Hugo"
homepage = "http://virtumaster.com"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Jon Harris"
  homepage = "http://virtumaster.com"
